amcl:
  ros__parameters:
    use_map_topic: false
    first_map_only: false
    save_pose_rate: 0.5
    laser_max_range: 3.0
    laser_min_range: 0.1
    laser_max_beams: 60
    laser_z_hit: 0.95
    laser_z_short: 0.1
    laser_z_max: 0.05 # how much weight on far readings, 'higher => trusts empty space more'
    laser_z_rand: 0.05
    laser_sigma_hit: 0.6 # how strict the robot is about matching up lidar readings
    laser_lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    update_min_d: 0.25
    update_min_a: 0.2
    resample_interval: 1
    transform_tolerance: 1.0 # seconds between updating transform
    recovery_alpha_slow: 0.001
    recovery_alpha_fast: 0.1  # aggressive and possibly unstable localisation
    tf_broadcast: true

    # Frame IDs
    odom_frame_id: "odom"
    base_frame_id: "base_link"
    global_frame_id: "map"

    # Particle filter settings
    min_particles: 500
    max_particles: 2000
    pf_err: 0.05
    pf_z: 0.99

    # Motion model noise parameters
    alpha1: 0.6 # rotation affect on heading est. -> trying to counter angular misalignment 
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.6 # rotation affect on coord. est. -> trying to counter angular misalignment
